# This workflow will install Python dependencies & run quality checks

name: CI-python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "poetry"

    - name: Install app & dependencies
      run: poetry install

    - name: Check precommit hooks
      uses: pre-commit/action@v3.0.0

    - run: poetry run pytest .

    - name: smoke test - validate modeling input schema v1.0.0
      run: poetry run raven-schemas validate-file -s modeling_input -f raven_schemas/schemas/modeling_input_1_0_0_sample_valid.json -v 1.0.0
